name: Cypress Tests for PR

on:
  pull_request:
    branches:
      - main  # Ou a branch que você está usando como base para os PRs

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]  # Ajuste conforme necessário
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: http://localhost:3000  # Ajuste a porta conforme necessário
          wait-on-timeout: 120  # Tempo em segundos para aguardar o servidor iniciar
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Cypress Reports
        uses: actions/upload-artifact@v3
        with:
          name: cypress-reports
          path: |
            cypress/screenshots
            cypress/videos
